### PR TITLE
Bump runtime to 23.08

### PR DESCRIPTION
**Pull request by muelli**
https://github.com/flathub/net.codeindustry.MasterPDFEditor/issues/80

### CODE REVIEW

**Comment by muelli** [comment]
@gnumanx can you try whether this works well enough for you?

**Comment by gnumanx** [comment]
the link returns 404

**Comment by x80486** [comment]
Should you give it another whirl to a new build?

**Comment by muelli** [comment]
bot, build

**Comment by x80486** [comment]
@muelli, since this is ready, whenever you have some time can you merge it?

**Comment by muelli** [comment]
@x80486 can you try whether it works well enough for you? I would like to avoid shipping broken builds.

**Comment by x80486** [comment]
The resource identified by the link is dead now. I think I tested this — but there has been quite a bit of these lately, so I can't remember for sure. If you trigger another build, I can install and check that it opens up properly and some basic functionality is still intact.

**Comment by nr23730** [comment]
@muelli 
I did a local build of this and confirm this is working. :)

**Review by nr23730 — APPROVED** [review]

**Pull request merged**
